version: '3'

services:
    web:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - '8080:80'
        volumes:
            - '.:/app/'
        depends_on:
            - 'php'
            - 'db'
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        expose:
          - 9000
        volumes:
            - '.:/app/'
            # - './docker/php/conf.d/:/usr/local/etc/php/conf.d/'
    db:
        image: postgres:15.1-alpine
        restart: always
        environment:
            - POSTGRES_DB=$DB_NAME
            - POSTGRES_USER=$DB_USER
            - POSTGRES_PASSWORD=$DB_PASSWORD
        ports:
            - '5432:5432'
        volumes:
            - 'pgdata:/var/lib/postgresql/data'
            - './docker/postgres/:/docker-entrypoint-initdb.d/'
volumes:
    pgdata:
        external: true